Github action Workflow Updated: some debugging

diff --git a/.github/workflows/debug-deploy.yml b/.github/workflows/debug-deploy.yml
--- a/.github/workflows/debug-deploy.yml
+++ b/.github/workflows/debug-deploy.yml
@@ -10,28 +10,32 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     container: ghcr.io/railwayapp/cli:latest
+    environment: production
     env:
-      SVC_ID: my-service
+      SVC_ID: d8f2b40a-b9bf-49ae-84d4-2ad5fd3a379f
       RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
 
     steps:
-    - name: Create Dockerfile from Docker Hub image
-      run: |
-        echo "FROM ashishv01/facedec:latest" > Dockerfile
+      - name: Create Dockerfile from Docker Hub image
+        run: |
+          echo "FROM ashishv01/facedec:latest" > Dockerfile
 
-    - name: Is token available
-      run: |
-        if [ -n "$RAILWAY_TOKEN" ]; then 
-          echo "Token is there";
-        else 
-          echo "Token not found";
-          exit 1
-        fi
+      - name: Is token available
+        run: |
+          if [ -n "$RAILWAY_TOKEN" ]; then 
+            echo "Token is there";
+          else 
+            echo "Token not found";
+            exit 1
+          fi
 
-    - name: Checking repo
-      run: |
-        ls -al
-        cat Dockerfile
+      - name: Checking repo
+        run: |
+          ls -al
+          cat Dockerfile
 
-    - name: Deploy to Railway
-      run: railway up --service d8f2b40a-b9bf-49ae-84d4-2ad5fd3a379f
+      - name: Check out Github
+        uses: actions/checkout@v3
+
+      - name: Deploy to Railway
+        run: railway up --service=${{ env.SVC_ID }}
