Github action Workflow Updated: some debugging

diff --git a/.github/workflows/debug-deploy.yml b/.github/workflows/debug-deploy.yml
--- a/.github/workflows/debug-deploy.yml
+++ b/.github/workflows/debug-deploy.yml
@@ -12,12 +12,21 @@ jobs:
     container: ghcr.io/railwayapp/cli:latest
     env:
       SVC_ID: my-service
-      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
+      RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
 
     steps:
     - name: Create Dockerfile from Docker Hub image
       run: |
         echo "FROM ashishv01/facedec:latest" > Dockerfile
+
+    - name: Is token available
+      run: |
+        if [ $RAILWAY_TOKEN != null ]; then 
+          echo "Token is there";
+        else 
+          echo "Token not found";
+          exit 1
+        fi
 
     - name: Checking repo
       run: |
@@ -25,6 +34,4 @@ jobs:
         cat Dockerfile
 
     - name: Deploy to Railway
-      env:
-        RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
       run: railway up --service d8f2b40a-b9bf-49ae-84d4-2ad5fd3a379f
